/** Closed set of reasons either side may give for calling off a donation. */
export enum CancellationReasonCode {
  CANNOT_MAKE_WINDOW = 'CANNOT_MAKE_WINDOW',
  VEHICLE_BREAKDOWN = 'VEHICLE_BREAKDOWN',
  VEHICLE_CAPACITY_REACHED = 'VEHICLE_CAPACITY_REACHED',
  STORAGE_CAPACITY_REACHED = 'STORAGE_CAPACITY_REACHED',
  STORE_LOGISTICS_DELAY = 'STORE_LOGISTICS_DELAY',
  NO_LONGER_NEEDED = 'NO_LONGER_NEEDED',
  DRIVER_NO_SHOW = 'DRIVER_NO_SHOW',
  OTHER = 'OTHER',
}

export const CANCELLATION_REASON_CODE_ENUM_NAME = 'cancellation_reason_code';
