/** What kind of business the retailer runs. */
export enum BusinessType {
  SUPERMARKET = 'SUPERMARKET',
  HYPERMARKET = 'HYPERMARKET',
  RESTAURANT = 'RESTAURANT',
  HOTEL = 'HOTEL',
  BAKERY = 'BAKERY',
  CATERING = 'CATERING',
  DISTRIBUTOR = 'DISTRIBUTOR',
  MANUFACTURER = 'MANUFACTURER',
  FARM = 'FARM',
  CORPORATE_CAFETERIA = 'CORPORATE_CAFETERIA',
  CONVENIENCE_STORE = 'CONVENIENCE_STORE',
  OTHER = 'OTHER',
}

export const BUSINESS_TYPE_ENUM_NAME = 'retailer_business_type';
